version: 2
jobs:
  build:
    docker:
      - image: ghcr.io/gbdev/rgbds:v0.9.3
    steps:
      - checkout
      - run:
          name: Installing build dependencies
          command: apt-get update && apt-get --yes install python3-minimal
      - run:
          name: Building
          command: make build-all
      - run:
          name: Testing checksum
          command: make test-all
